### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by jimeh** [krystal/go-katapult#64]
Handling of error responses from Katapult's API isn't great right now, as we
don't actually parse the detail attribute due to the type being different
depending on the type of error.

To address this, we need to create a whole series of error structs that match up
against all of the error types the Katapult API can return, which are capable of
parsing the `detail` property according to the the type of that error. These
errors should also conform to the `error` interface, where the `Error()` method
returns a sensible string version of itself, taking `code`, `description`, and
`detail` values into account. These custom error structs should also implement
`Unwrap()` and `Is()` methods, and act as if they've wrapped a standard error
var.

The existing `ResponseError` structs will then be used to initially parse the
returned JSON response, and based on the `Code` field, we initialize the
relevant error struct, having it parse the `Detail json.RawMessage` field.

All API methods which currently return a stuct, `Response`, and `error` should
then be changed, so the `error` is actually the parsed error struct.

As an example, right now if you get a error back, but want custom logic if it is
a 404 not found error, something like this must be done:

```go
ip, resp, err := client.IPAddresses.GetByID(ctx, "ip_r3NoJOsbEtZOwT89")
if err != nil {
	if resp != nil && resp.Response && resp.StatusCode != 404 {
		// do something for not found errors
	} else {
		// do something for any other error
	}
}
```

The above is rather cumbersome and annoying, instead I would like to be able to
do something like this:

```go
ip, resp, err := client.IPAddresses.GetByID(ctx, "ip_r3NoJOsbEtZOwT89")
if err != nil {
	if errors.Is(err, katapult.ErrNotFound) {
		// do something for not found errors
	} else {
		// do something for any other error
	}
}
```

Errors should also have a multiple levels of wrapping, so in the above example,
`err` is all of the following when checked with `errors.Is()`:

- `katapult.ErrIPAddressNotFound`
- `katapult.ErrNotFound`
- `katapult.Err`

As a final note, once errors are actually returned as the `error` return value,
the `Response` return value should probably be refactored into some form of
"meta" object, as it'll mostly just be needed for pagination details, rate
limits, and other such "meta" about the response.

**Comment by strideynet** [comment]
I think as part of this work, it would be reasonable for us to remove the "Response" object and instead integrate this data (where necessary) into the first returned value: e.g

```go
type LoadBalancerList struct {
  katapult.Pagination
  Items []LoadBalancer
}
func (lbc *LoadBalancerClient) List(ctx context.Context, someListOptions optionType) (LoadBalancerList, error) {

}
```

I think for a majority of cases, we will find that no such "meta" exists, and in many ways I prefer to keep our types relatively scoped and purposeful and "meta" very quickly becomes fluffy, and unpredictable.


We should also take care to refactor some of the error return behaviour when we refactor the errors. As it stands, we tend to return pointers to values in places where we could probably be better served by just returning nil and err. This makes the library simpler to consume as the returned data is either alright or error, and there's no middle state.
