### ISSUE TITLE
Add support for Firewalls

### ISSUE THREAD

**Issue by jimeh** [krystal/go-katapult#71]
**Note:** Firewalls may soon be superseded in Katapult by "Security Groups",
which would offer more flexibility than the current Firewall system. Hence this
feature is on hold for now.

---

Add support for Firewall and Firewall Rule operations.

API documentation:

- Firewalls: https://developers.katapult.io/api/docs/latest/groups/firewalls/
- Firewall Rules:
  https://developers.katapult.io/api/docs/latest/groups/firewalls/rules/

**Comment by strideynet** [comment]
Security groups are being introduced.
