### ISSUE TITLE
Add support for Load Balancer Rule operations

### ISSUE THREAD

**Issue by jimeh** [krystal/go-katapult#72]
Basic CRUD operations for Load Balancers is already available. But they are not
all that useful until you can also manage Load Balancer Rules.

Hence we need to add support for all the rule operations available in the API:
https://developers.katapult.io/api/docs/latest/groups/load_balancers/rules/

**Comment by andrewjtait** [comment]
@jimeh will this also require support for creating certificates?

**Comment by jimeh** [comment]
@andrewjtait indeed we probably will. Though the [Core API](https://developers.katapult.io/api/docs/latest/groups/certificates/) doesn't support that at the moment, so probably a discussion we need to have with @adamcooke.

**Comment by strideynet** [comment]
This is blocking work on KCE-CCM. I will take up this task.
